page:
  logo: 'http://fact.g0v.tw/logo.png'
  sitename: '政誌'
  mission: '勿忘政治'
  fb_appid: 113809385333711

index:
  _source: 'https://spreadsheets.google.com/feeds/list/0AuwTztKH2tKidGZ2cEdVY19PZEpzRWVJWWZOeUI1Y0E/od6/public/values?alt=json' # google spreadsheet json page

category:
  _source: 'https://spreadsheets.google.com/feeds/list/0AuwTztKH2tKidGZ2cEdVY19PZEpzRWVJWWZOeUI1Y0E/od7/public/values?alt=json' # google spreadsheet json page

wikipedia:
  _scheme: 'http://'
  _domain: 'zh.wikipedia.org' # can be other languages
  _render: 'w/index.php?&action=render&variant=zh-tw&title=' # page render main url, will append title
  _api: 'w/api.php?action={action}&prop={prop}&format=json&titles=' # api for render other page, return json format
  _minLength: 40 # page render main url

port: 8080
debug: false
